// videos.js — Video catalogue — real YouTube IDs. Thumbnails come from i.ytimg.com.

/* ---------- VIDEO CATALOGUE ---------- */
const VIDEOS = [
 // ---- Music ----
 {id:"dQw4w9WgXcQ",title:"Rick Astley - Never Gonna Give You Up (Official Video)",ch:"Rick Astley",cat:"Music",tags:["pop","80s","retro","classic"],views:1.5e9,age:"15 years ago",dur:"3:33"},
 {id:"9bZkp7q19f0",title:"PSY - GANGNAM STYLE(강남스타일) M/V",ch:"officialpsy",cat:"Music",tags:["kpop","dance","viral"],views:5.1e9,age:"12 years ago",dur:"4:13"},
 {id:"kJQP7kiw5Fk",title:"Luis Fonsi - Despacito ft. Daddy Yankee",ch:"Luis Fonsi",cat:"Music",tags:["latin","pop","dance"],views:8.4e9,age:"7 years ago",dur:"4:42"},
 {id:"OPf0YbXqDm0",title:"Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars",ch:"Mark Ronson",cat:"Music",tags:["funk","pop","dance"],views:5.2e9,age:"9 years ago",dur:"4:31"},
 {id:"fJ9rUzIMcZQ",title:"Queen – Bohemian Rhapsody (Official Video Remastered)",ch:"Queen Official",cat:"Music",tags:["rock","classic","70s"],views:1.9e9,age:"16 years ago",dur:"5:59"},
 {id:"HgzGwKwLmgM",title:"Queen - Don't Stop Me Now (Official Video)",ch:"Queen Official",cat:"Music",tags:["rock","classic","70s"],views:8.0e8,age:"16 years ago",dur:"3:36"},
 {id:"hTWKbfoikeg",title:"Nirvana - Smells Like Teen Spirit (Official Music Video)",ch:"Nirvana",cat:"Music",tags:["rock","grunge","90s"],views:1.8e9,age:"15 years ago",dur:"4:38"},
 {id:"YQHsXMglC9A",title:"Adele - Hello (Official Music Video)",ch:"Adele",cat:"Music",tags:["pop","ballad"],views:3.2e9,age:"8 years ago",dur:"6:07"},
 {id:"RgKAFK5djSk",title:"Wiz Khalifa - See You Again ft. Charlie Puth [Official Video] Furious 7 Soundtrack",ch:"Wiz Khalifa",cat:"Music",tags:["hiphop","pop","movies"],views:6.3e9,age:"9 years ago",dur:"3:58"},
 {id:"JGwWNGJdvx8",title:"Ed Sheeran - Shape of You (Official Music Video)",ch:"Ed Sheeran",cat:"Music",tags:["pop"],views:6.2e9,age:"7 years ago",dur:"4:24"},
 {id:"60ItHLz5WEA",title:"Alan Walker - Faded",ch:"Alan Walker",cat:"Music",tags:["edm","electronic"],views:3.6e9,age:"8 years ago",dur:"3:33"},
 {id:"nfWlot6h_JM",title:"Taylor Swift - Shake It Off",ch:"Taylor Swift",cat:"Music",tags:["pop","dance"],views:3.4e9,age:"10 years ago",dur:"4:02"},
 {id:"4NRXx6U8ABQ",title:"The Weeknd - Blinding Lights (Official Video)",ch:"The Weeknd",cat:"Music",tags:["pop","synthpop","80s"],views:9.0e8,age:"4 years ago",dur:"4:23"},
 {id:"DyDfgMOUjCI",title:"Billie Eilish - bad guy",ch:"Billie Eilish",cat:"Music",tags:["pop","alt"],views:1.4e9,age:"5 years ago",dur:"3:26"},
 {id:"TUVcZfQe-Kw",title:"Dua Lipa - Levitating Featuring DaBaby (Official Music Video)",ch:"Dua Lipa",cat:"Music",tags:["pop","disco","dance"],views:8.0e8,age:"4 years ago",dur:"3:23"},
 {id:"7wtfhZwyrcc",title:"Imagine Dragons - Believer (Official Music Video)",ch:"Imagine Dragons",cat:"Music",tags:["rock","alt"],views:2.6e9,age:"7 years ago",dur:"3:37"},
 {id:"ktvTqknDobU",title:"Imagine Dragons - Radioactive (Official Music Video)",ch:"Imagine Dragons",cat:"Music",tags:["rock","alt"],views:1.5e9,age:"11 years ago",dur:"3:11"},
 {id:"XbGs_qK2PQA",title:"Eminem - Rap God (Explicit) [Official Video]",ch:"Eminem",cat:"Music",tags:["hiphop","rap"],views:1.7e9,age:"10 years ago",dur:"6:04"},
 {id:"_Yhyp-_hX2s",title:"Eminem - Lose Yourself [HD]",ch:"Eminem",cat:"Music",tags:["hiphop","rap","movies"],views:1.2e9,age:"13 years ago",dur:"5:24"},
 {id:"jfKfPfyJRdk",title:"lofi hip hop radio 📚 beats to relax/study to",ch:"Lofi Girl",cat:"Music",tags:["lofi","chill","study"],views:1.2e9,age:"Streaming",dur:"LIVE"},
 {id:"gdZLi9oWNZg",title:"BTS (방탄소년단) 'Dynamite' Official MV",ch:"HYBE LABELS",cat:"Music",tags:["kpop","pop","dance"],views:1.9e9,age:"4 years ago",dur:"3:43"},
 {id:"IHNzOHi8sJs",title:"BLACKPINK - '뚜두뚜두 (DDU-DU DDU-DU)' M/V",ch:"BLACKPINK",cat:"Music",tags:["kpop","dance"],views:2.2e9,age:"6 years ago",dur:"3:35"},
 {id:"VYOjWnS4cMY",title:"Childish Gambino - This Is America (Official Video)",ch:"Donald Glover",cat:"Music",tags:["hiphop","rap"],views:9.5e8,age:"6 years ago",dur:"4:05"},
 {id:"FTQbiNvZqaY",title:"Toto - Africa (Official HD Video)",ch:"Toto",cat:"Music",tags:["80s","rock","classic","retro"],views:1.1e9,age:"11 years ago",dur:"4:33"},
 {id:"djV11Xbc914",title:"a-ha - Take On Me (Official Video) [Remastered in 4K]",ch:"a-ha",cat:"Music",tags:["80s","synthpop","retro"],views:2.0e9,age:"14 years ago",dur:"3:49"},
 {id:"1w7OgIMMRc4",title:"Guns N' Roses - Sweet Child O' Mine (Official Music Video)",ch:"Guns N' Roses",cat:"Music",tags:["rock","classic","80s"],views:1.7e9,age:"14 years ago",dur:"5:03"},
 {id:"kXYiU_JCYtU",title:"Numb (Official Music Video) [4K UPGRADE] – Linkin Park",ch:"Linkin Park",cat:"Music",tags:["rock","alt","2000s"],views:2.4e9,age:"17 years ago",dur:"3:07"},
 {id:"eVTXPUF4Oz4",title:"In The End [Official HD Music Video] - Linkin Park",ch:"Linkin Park",cat:"Music",tags:["rock","alt","2000s"],views:1.9e9,age:"17 years ago",dur:"3:38"},
 {id:"UqyT8IEBkvY",title:"Bruno Mars - 24K Magic (Official Music Video)",ch:"Bruno Mars",cat:"Music",tags:["funk","pop","dance"],views:1.8e9,age:"8 years ago",dur:"3:47"},
 {id:"L_jWHffIx5E",title:"Smash Mouth - All Star (Official Music Video)",ch:"Smash Mouth",cat:"Music",tags:["90s","rock","memes"],views:1.0e9,age:"15 years ago",dur:"3:57"},

 // ---- Education / Science ----
 {id:"aircAruvnKk",title:"But what is a neural network? | Deep learning chapter 1",ch:"3Blue1Brown",cat:"Education",tags:["ai","math","deeplearning","coding"],views:1.8e7,age:"6 years ago",dur:"18:40"},
 {id:"IHZwWFHWa-w",title:"Gradient descent, how neural networks learn | Deep learning chapter 2",ch:"3Blue1Brown",cat:"Education",tags:["ai","math","deeplearning"],views:7.0e6,age:"6 years ago",dur:"20:33"},
 {id:"WUvTyaaNkzM",title:"The essence of calculus",ch:"3Blue1Brown",cat:"Education",tags:["math","calculus"],views:9.0e6,age:"7 years ago",dur:"17:04"},
 {id:"fNk_zzaMoSs",title:"Vectors | Chapter 1, Essence of linear algebra",ch:"3Blue1Brown",cat:"Education",tags:["math","linearalgebra"],views:8.0e6,age:"8 years ago",dur:"9:52"},
 {id:"sNhhvQGsMEc",title:"The Fermi Paradox — Where Are All The Aliens? (1/2)",ch:"Kurzgesagt – In a Nutshell",cat:"Science",tags:["space","aliens","science","animation"],views:3.0e7,age:"9 years ago",dur:"6:07"},
 {id:"h6fcK_fRYaI",title:"The Egg - A Short Story",ch:"Kurzgesagt – In a Nutshell",cat:"Science",tags:["philosophy","story","animation"],views:4.0e7,age:"5 years ago",dur:"7:56"},
 {id:"MBRqu0YOH14",title:"Optimistic Nihilism",ch:"Kurzgesagt – In a Nutshell",cat:"Science",tags:["philosophy","animation"],views:2.0e7,age:"7 years ago",dur:"6:09"},
 {id:"zQGOcOUBi6s",title:"The Immune System Explained I – Bacteria Infection",ch:"Kurzgesagt – In a Nutshell",cat:"Science",tags:["biology","science","animation"],views:3.0e7,age:"10 years ago",dur:"6:48"},
 {id:"1AElONvi9WQ",title:"Why Blue Whales Don't Get Cancer - Peto's Paradox",ch:"Kurzgesagt – In a Nutshell",cat:"Science",tags:["biology","science","animation"],views:1.5e7,age:"5 years ago",dur:"9:04"},
 {id:"ijFm6DxNVyI",title:"The Most Efficient Way to Destroy the Universe – False Vacuum",ch:"Kurzgesagt – In a Nutshell",cat:"Science",tags:["physics","space","animation"],views:2.0e7,age:"8 years ago",dur:"5:51"},
 {id:"IgF3OX8nT0w",title:"The Most Powerful Computers You've Never Heard Of",ch:"Veritasium",cat:"Science",tags:["tech","computing","history"],views:8.0e6,age:"3 years ago",dur:"20:04"},
 {id:"uxPdPpi5W4o",title:"Why Are 96,000,000 Black Balls on This Reservoir?",ch:"Veritasium",cat:"Science",tags:["science","engineering"],views:1.0e8,age:"5 years ago",dur:"12:00"},
 {id:"OxGsU8oIWjY",title:"How An Infinite Hotel Ran Out Of Room",ch:"Veritasium",cat:"Science",tags:["math","infinity"],views:3.0e7,age:"3 years ago",dur:"6:06"},
 {id:"MFzDaBzBlL0",title:"The Backwards Brain Bicycle - Smarter Every Day 133",ch:"SmarterEveryDay",cat:"Science",tags:["science","brain","experiment"],views:3.0e7,age:"9 years ago",dur:"7:57"},
 {id:"xe-f4gokRBs",title:"Mystery of Prince Rupert's Drop at 130,000 fps - Smarter Every Day 86",ch:"SmarterEveryDay",cat:"Science",tags:["science","physics","slowmo","experiment"],views:3.0e7,age:"11 years ago",dur:"7:41"},
 {id:"jHbyQ_AQP8c",title:"What If Everyone JUMPED At Once?",ch:"Vsauce",cat:"Science",tags:["science","physics"],views:4.0e7,age:"12 years ago",dur:"6:14"},
 {id:"UF8uR6Z6KLc",title:"Steve Jobs' 2005 Stanford Commencement Address",ch:"Stanford",cat:"Education",tags:["tech","inspiration","speech"],views:4.5e7,age:"16 years ago",dur:"15:04"},
 {id:"kYB8IZa5AuE",title:"Linus Torvalds: The mind behind Linux | TED",ch:"TED",cat:"Education",tags:["tech","linux","opensource","coding","speech"],views:8.0e6,age:"8 years ago",dur:"21:31"},

 // ---- Coding ----
 {id:"rfscVS0vtbw",title:"Learn Python - Full Course for Beginners [Tutorial]",ch:"freeCodeCamp.org",cat:"Coding",tags:["coding","python","tutorial"],views:4.5e7,age:"6 years ago",dur:"4:26:52"},
 {id:"PkZNo7MFNFg",title:"Learn JavaScript - Full Course for Beginners",ch:"freeCodeCamp.org",cat:"Coding",tags:["coding","javascript","tutorial"],views:1.5e7,age:"5 years ago",dur:"3:26:43"},
 {id:"w7ejDZ8SWv8",title:"React JS Crash Course",ch:"Traversy Media",cat:"Coding",tags:["coding","javascript","react","tutorial"],views:4.0e6,age:"3 years ago",dur:"1:48:48"},
 {id:"DHjqpvDnNGE",title:"JavaScript in 100 Seconds",ch:"Fireship",cat:"Coding",tags:["coding","javascript","short"],views:3.0e6,age:"3 years ago",dur:"2:12"},
 {id:"Tn6-PIqc4UM",title:"React in 100 Seconds",ch:"Fireship",cat:"Coding",tags:["coding","react","javascript","short"],views:2.0e6,age:"3 years ago",dur:"2:07"},
 {id:"5C_HPTJg5ek",title:"Rust in 100 Seconds",ch:"Fireship",cat:"Coding",tags:["coding","rust","short"],views:2.0e6,age:"3 years ago",dur:"2:44"},
 {id:"Gjnup-PuquQ",title:"Docker in 100 Seconds",ch:"Fireship",cat:"Coding",tags:["coding","devops","short"],views:2.0e6,age:"3 years ago",dur:"2:19"},
 {id:"x7X9w_GIm1s",title:"Python in 100 Seconds",ch:"Fireship",cat:"Coding",tags:["coding","python","short"],views:3.0e6,age:"3 years ago",dur:"2:24"},

 // ---- Gaming ----
 {id:"MmB9b5njVbA",title:"Minecraft Trailer",ch:"Minecraft",cat:"Gaming",tags:["minecraft","sandbox","gaming"],views:4.0e7,age:"12 years ago",dur:"1:36"},
 {id:"QkkoHAzjnUs",title:"Grand Theft Auto V: The Official Trailer",ch:"Rockstar Games",cat:"Gaming",tags:["gta","openworld","gaming","trailer"],views:9.0e7,age:"11 years ago",dur:"1:05"},
 {id:"E3Huy2cdih0",title:"ELDEN RING – Official Gameplay Reveal",ch:"BANDAI NAMCO Entertainment",cat:"Gaming",tags:["rpg","fromsoftware","gaming","trailer"],views:1.5e7,age:"3 years ago",dur:"3:07"},
 {id:"1rPxiXXxftE",title:"The Legend of Zelda: Breath of the Wild – Nintendo Switch Presentation 2017 Trailer",ch:"Nintendo",cat:"Gaming",tags:["zelda","nintendo","adventure","gaming","trailer"],views:3.0e7,age:"7 years ago",dur:"3:34"},
 {id:"8X2kIfS6fb8",title:"Cyberpunk 2077 – Official E3 2018 Trailer",ch:"Cyberpunk 2077",cat:"Gaming",tags:["rpg","scifi","gaming","trailer"],views:2.5e7,age:"6 years ago",dur:"2:16"},
 {id:"O2W0N3GKPh4",title:"Half-Life: Alyx Announcement Trailer",ch:"Valve",cat:"Gaming",tags:["vr","fps","gaming","trailer"],views:1.5e7,age:"4 years ago",dur:"1:59"},
 {id:"0e3GPea1Tyg",title:"$456,000 Squid Game In Real Life!",ch:"MrBeast",cat:"Entertainment",tags:["challenge","mrbeast","entertainment"],views:6.0e8,age:"2 years ago",dur:"25:41"},
 {id:"9bqk6ZUsKyA",title:"I Spent 50 Hours Buried Alive",ch:"MrBeast",cat:"Entertainment",tags:["challenge","mrbeast","entertainment"],views:3.0e8,age:"3 years ago",dur:"12:53"},
 {id:"xoxhDk-hwuo",title:"Package Thief vs. Glitter Bomb Trap",ch:"Mark Rober",cat:"Entertainment",tags:["engineering","prank","diy","entertainment"],views:1.0e8,age:"5 years ago",dur:"10:56"},
 {id:"hFZFjoX2cGg",title:"Building the Perfect Squirrel Proof Bird Feeder",ch:"Mark Rober",cat:"Entertainment",tags:["engineering","diy","animals","entertainment"],views:1.0e8,age:"4 years ago",dur:"21:41"},

 // ---- Movies ----
 {id:"zSWdZVtXT7E",title:"Interstellar - Official Trailer",ch:"Warner Bros. Pictures",cat:"Movies",tags:["scifi","nolan","trailer","space"],views:3.0e7,age:"10 years ago",dur:"2:31"},
 {id:"YoHD9XEInc0",title:"Inception - Official Trailer [HD]",ch:"Warner Bros. Pictures",cat:"Movies",tags:["scifi","nolan","trailer","thriller"],views:2.0e7,age:"14 years ago",dur:"2:25"},
 {id:"EXeTwQWrcwY",title:"The Dark Knight (2008) Official Trailer #1",ch:"Warner Bros. Pictures",cat:"Movies",tags:["batman","nolan","superhero","trailer"],views:2.0e7,age:"11 years ago",dur:"2:13"},
 {id:"TcMBFSGVi1c",title:"Marvel Studios' Avengers: Endgame - Official Trailer",ch:"Marvel Entertainment",cat:"Movies",tags:["marvel","superhero","trailer","action"],views:1.5e8,age:"5 years ago",dur:"2:26"},
 {id:"uYPbbksJxIg",title:"Oppenheimer | Official Trailer",ch:"Universal Pictures",cat:"Movies",tags:["nolan","drama","history","trailer"],views:3.0e7,age:"1 year ago",dur:"3:11"},
 {id:"pBk4NYhWNMM",title:"Barbie | Main Trailer",ch:"Warner Bros. Pictures",cat:"Movies",tags:["comedy","trailer"],views:4.0e7,age:"1 year ago",dur:"2:36"},
 {id:"Way9Dexny3w",title:"Dune: Part Two | Official Trailer",ch:"Warner Bros. Pictures",cat:"Movies",tags:["scifi","epic","trailer","space"],views:4.0e7,age:"1 year ago",dur:"3:03"},
 {id:"cqGjhVJWtEg",title:"SPIDER-MAN: ACROSS THE SPIDER-VERSE - Official Trailer #2",ch:"Sony Pictures Entertainment",cat:"Movies",tags:["animation","marvel","superhero","trailer"],views:4.0e7,age:"1 year ago",dur:"2:52"},
 {id:"qSqVVswa420",title:"Top Gun: Maverick | Official Trailer",ch:"Paramount Pictures",cat:"Movies",tags:["action","aviation","trailer"],views:4.0e7,age:"2 years ago",dur:"2:19"},
 {id:"sGbxmsDFVnE",title:"Star Wars: The Force Awakens Trailer (Official)",ch:"Star Wars",cat:"Movies",tags:["starwars","scifi","trailer","space"],views:1.0e8,age:"8 years ago",dur:"2:35"},
 {id:"urRVZ4SW7WU",title:"Free Solo - Trailer | National Geographic",ch:"National Geographic",cat:"Movies",tags:["documentary","climbing","adventure","trailer"],views:5.0e6,age:"6 years ago",dur:"2:35"},

 // ---- Comedy / viral ----
 {id:"Dd7FixvoKBw",title:"Key & Peele - Substitute Teacher",ch:"Comedy Central",cat:"Comedy",tags:["sketch","comedy"],views:2.0e8,age:"11 years ago",dur:"3:03"},
 {id:"_OBlgSz8sSM",title:"Charlie bit my finger - again !",ch:"HDCYT",cat:"Comedy",tags:["viral","kids","classic"],views:9.0e8,age:"17 years ago",dur:"0:56"},
 {id:"EwTZ2xpQwpA",title:"\"Chocolate Rain\" Original Song by Tay Zonday",ch:"TayZonday",cat:"Comedy",tags:["viral","music","memes"],views:1.4e8,age:"17 years ago",dur:"4:52"},
 {id:"J---aiyznGQ",title:"Keyboard Cat! - THE ORIGINAL!",ch:"Keyboard Cat!",cat:"Comedy",tags:["viral","cats","memes","animals"],views:7.0e7,age:"17 years ago",dur:"0:55"},
 {id:"a1Y73sPHKxw",title:"Dramatic Chipmunk",ch:"Magnets99",cat:"Comedy",tags:["viral","animals","memes"],views:6.0e7,age:"17 years ago",dur:"0:06"},
 {id:"QH2-TGUlwu4",title:"Nyan Cat [original]",ch:"saraj00n",cat:"Comedy",tags:["viral","memes","cats"],views:2.0e8,age:"13 years ago",dur:"3:37"},
 {id:"OQSNhk5ICTI",title:"Yosemitebear Mountain Double Rainbow 1-8-10",ch:"Yosemitebear62",cat:"Comedy",tags:["viral","nature","memes"],views:5.0e7,age:"14 years ago",dur:"3:30"},
 {id:"txqiwrbYGrs",title:"David After Dentist",ch:"booba1234",cat:"Comedy",tags:["viral","kids","memes"],views:1.4e8,age:"15 years ago",dur:"1:59"},

 // ---- Cooking / Fitness / Nature / Space ----
 {id:"PUP7U5vTMM0",title:"Gordon Ramsay's Scrambled Eggs",ch:"Gordon Ramsay",cat:"Cooking",tags:["cooking","breakfast","recipe"],views:5.0e7,age:"13 years ago",dur:"3:35"},
 {id:"AmC9SmCBUj4",title:"How To Cook The Perfect Steak - Gordon Ramsay",ch:"Gordon Ramsay",cat:"Cooking",tags:["cooking","steak","recipe"],views:2.0e7,age:"12 years ago",dur:"3:41"},
 {id:"v7AYKMP6rOE",title:"Yoga For Complete Beginners - 20 Minute Home Yoga Workout!",ch:"Yoga With Adriene",cat:"Fitness",tags:["yoga","fitness","wellness"],views:5.0e7,age:"11 years ago",dur:"22:40"},
 {id:"2pLT-olgUJs",title:"Get Abs in 2 WEEKS | Abs Workout Challenge",ch:"Chloe Ting",cat:"Fitness",tags:["fitness","workout","abs"],views:5.0e8,age:"5 years ago",dur:"11:59"},
 {id:"c8aFcHFu8QM",title:"Planet Earth II: Official Extended Trailer - BBC Earth",ch:"BBC Earth",cat:"Nature",tags:["nature","documentary","animals"],views:2.0e7,age:"8 years ago",dur:"4:10"},
 {id:"aETNYyrqNYE",title:"Our Planet | Official Trailer [HD] | Netflix",ch:"Netflix",cat:"Nature",tags:["nature","documentary","animals"],views:1.0e7,age:"5 years ago",dur:"2:26"},
 {id:"4czjS9h4Fpg",title:"Perseverance Rover's Descent and Touchdown on Mars (Official NASA Video)",ch:"NASA",cat:"Space",tags:["space","mars","nasa","science"],views:2.0e7,age:"3 years ago",dur:"3:25"},
 {id:"wbSwFU6tY1c",title:"Falcon Heavy Test Flight",ch:"SpaceX",cat:"Space",tags:["space","rocket","spacex","engineering"],views:3.0e7,age:"6 years ago",dur:"36:58"},
];
const byId = Object.fromEntries(VIDEOS.map(v=>[v.id,v]));
const CATS = ["All",...new Set(VIDEOS.map(v=>v.cat))];
